library(sf)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(plotly)
library(readxl)
library(readr)
library(stringr)


# Leo todos los archivos de sucursales
sucursales_3 <- read_delim("bases/sepa_1_comercio-sepa-3_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_4 = read_delim("bases/sepa_1_comercio-sepa-4_2024-09-12_09-05-11/sucursales.csv", 
                          delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                               id_bandera = col_character(), id_sucursal = col_character(), 
                                                                               sucursales_nombre = col_character(), 
                                                                               sucursales_tipo = col_character(), 
                                                                               sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                               sucursales_latitud = col_double(), 
                                                                               sucursales_longitud = col_double(), 
                                                                               sucursales_observaciones = col_skip(), 
                                                                               sucursales_codigo_postal = col_skip(), 
                                                                               sucursales_localidad = col_character(), 
                                                                               sucursales_provincia = col_character(), 
                                                                               sucursales_lunes_horario_atencion = col_character(), 
                                                                               sucursales_martes_horario_atencion = col_character(), 
                                                                               sucursales_miercoles_horario_atencion = col_character(), 
                                                                               sucursales_jueves_horario_atencion = col_character(), 
                                                                               sucursales_viernes_horario_atencion = col_character(), 
                                                                               sucursales_sabado_horario_atencion = col_character(), 
                                                                               sucursales_domingo_horario_atencion = col_character()), 
                          trim_ws = TRUE)
sucursales_9 = read_delim("bases/sepa_1_comercio-sepa-9_2024-09-12_09-05-11/sucursales.csv", 
                          delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                               id_bandera = col_character(), id_sucursal = col_character(), 
                                                                               sucursales_nombre = col_character(), 
                                                                               sucursales_tipo = col_character(), 
                                                                               sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                               sucursales_latitud = col_double(), 
                                                                               sucursales_longitud = col_double(), 
                                                                               sucursales_observaciones = col_skip(), 
                                                                               sucursales_codigo_postal = col_skip(), 
                                                                               sucursales_localidad = col_character(), 
                                                                               sucursales_provincia = col_character(), 
                                                                               sucursales_lunes_horario_atencion = col_character(), 
                                                                               sucursales_martes_horario_atencion = col_character(), 
                                                                               sucursales_miercoles_horario_atencion = col_character(), 
                                                                               sucursales_jueves_horario_atencion = col_character(), 
                                                                               sucursales_viernes_horario_atencion = col_character(), 
                                                                               sucursales_sabado_horario_atencion = col_character(), 
                                                                               sucursales_domingo_horario_atencion = col_character()), 
                          trim_ws = TRUE)
sucursales_12 = read_delim("bases/sepa_1_comercio-sepa-12_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_15 = read_delim("bases/sepa_1_comercio-sepa-15_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_16 = read_delim("bases/sepa_1_comercio-sepa-16_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_19 = read_delim("bases/sepa_1_comercio-sepa-19_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_20 = read_delim("bases/sepa_1_comercio-sepa-20_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_21 = read_delim("bases/sepa_1_comercio-sepa-21_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_23 = read_delim("bases/sepa_1_comercio-sepa-23_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_35 = read_delim("bases/sepa_1_comercio-sepa-35_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_47 = read_delim("bases/sepa_1_comercio-sepa-47_2024-09-12_09-05-11/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_1000 = read_delim("bases/sepa_1_comercio-sepa-1000_2024-09-12_09-05-11/sucursales.csv", 
                             delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                  id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                  sucursales_nombre = col_character(), 
                                                                                  sucursales_tipo = col_character(), 
                                                                                  sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                  sucursales_latitud = col_double(), 
                                                                                  sucursales_longitud = col_double(), 
                                                                                  sucursales_observaciones = col_skip(), 
                                                                                  sucursales_codigo_postal = col_skip(), 
                                                                                  sucursales_localidad = col_character(), 
                                                                                  sucursales_provincia = col_character(), 
                                                                                  sucursales_lunes_horario_atencion = col_character(), 
                                                                                  sucursales_martes_horario_atencion = col_character(), 
                                                                                  sucursales_miercoles_horario_atencion = col_character(), 
                                                                                  sucursales_jueves_horario_atencion = col_character(), 
                                                                                  sucursales_viernes_horario_atencion = col_character(), 
                                                                                  sucursales_sabado_horario_atencion = col_character(), 
                                                                                  sucursales_domingo_horario_atencion = col_character()), 
                             trim_ws = TRUE)
sucursales_2000 = read_delim("bases/sepa_1_comercio-sepa-2000_2024-09-12_09-05-11/sucursales.csv", 
                             delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                  id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                  sucursales_nombre = col_character(), 
                                                                                  sucursales_tipo = col_character(), 
                                                                                  sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                  sucursales_latitud = col_double(), 
                                                                                  sucursales_longitud = col_double(), 
                                                                                  sucursales_observaciones = col_skip(), 
                                                                                  sucursales_codigo_postal = col_skip(), 
                                                                                  sucursales_localidad = col_character(), 
                                                                                  sucursales_provincia = col_character(), 
                                                                                  sucursales_lunes_horario_atencion = col_character(), 
                                                                                  sucursales_martes_horario_atencion = col_character(), 
                                                                                  sucursales_miercoles_horario_atencion = col_character(), 
                                                                                  sucursales_jueves_horario_atencion = col_character(), 
                                                                                  sucursales_viernes_horario_atencion = col_character(), 
                                                                                  sucursales_sabado_horario_atencion = col_character(), 
                                                                                  sucursales_domingo_horario_atencion = col_character()), 
                             trim_ws = TRUE)
sucursales_2005 = read_delim("bases/sepa_1_comercio-sepa-2005_2024-09-12_09-05-11/sucursales.csv", 
                             delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                  id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                  sucursales_nombre = col_character(), 
                                                                                  sucursales_tipo = col_character(), 
                                                                                  sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                  sucursales_latitud = col_double(), 
                                                                                  sucursales_longitud = col_double(), 
                                                                                  sucursales_observaciones = col_skip(), 
                                                                                  sucursales_codigo_postal = col_skip(), 
                                                                                  sucursales_localidad = col_character(), 
                                                                                  sucursales_provincia = col_character(), 
                                                                                  sucursales_lunes_horario_atencion = col_character(), 
                                                                                  sucursales_martes_horario_atencion = col_character(), 
                                                                                  sucursales_miercoles_horario_atencion = col_character(), 
                                                                                  sucursales_jueves_horario_atencion = col_character(), 
                                                                                  sucursales_viernes_horario_atencion = col_character(), 
                                                                                  sucursales_sabado_horario_atencion = col_character(), 
                                                                                  sucursales_domingo_horario_atencion = col_character()), 
                             trim_ws = TRUE)
sucursales_2007 = read_delim("bases/sepa_1_comercio-sepa-2007_2024-09-12_09-05-11/sucursales.csv", 
                             delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                  id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                  sucursales_nombre = col_character(), 
                                                                                  sucursales_tipo = col_character(), 
                                                                                  sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                  sucursales_latitud = col_double(), 
                                                                                  sucursales_longitud = col_double(), 
                                                                                  sucursales_observaciones = col_skip(), 
                                                                                  sucursales_codigo_postal = col_skip(), 
                                                                                  sucursales_localidad = col_character(), 
                                                                                  sucursales_provincia = col_character(), 
                                                                                  sucursales_lunes_horario_atencion = col_character(), 
                                                                                  sucursales_martes_horario_atencion = col_character(), 
                                                                                  sucursales_miercoles_horario_atencion = col_character(), 
                                                                                  sucursales_jueves_horario_atencion = col_character(), 
                                                                                  sucursales_viernes_horario_atencion = col_character(), 
                                                                                  sucursales_sabado_horario_atencion = col_character(), 
                                                                                  sucursales_domingo_horario_atencion = col_character()), 
                             trim_ws = TRUE)
sucursales_2011 = read_delim("bases/sepa_1_comercio-sepa-2011_2024-09-12_09-05-11/sucursales.csv", 
                             delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                  id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                  sucursales_nombre = col_character(), 
                                                                                  sucursales_tipo = col_character(), 
                                                                                  sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                  sucursales_latitud = col_double(), 
                                                                                  sucursales_longitud = col_double(), 
                                                                                  sucursales_observaciones = col_skip(), 
                                                                                  sucursales_codigo_postal = col_skip(), 
                                                                                  sucursales_localidad = col_character(), 
                                                                                  sucursales_provincia = col_character(), 
                                                                                  sucursales_lunes_horario_atencion = col_character(), 
                                                                                  sucursales_martes_horario_atencion = col_character(), 
                                                                                  sucursales_miercoles_horario_atencion = col_character(), 
                                                                                  sucursales_jueves_horario_atencion = col_character(), 
                                                                                  sucursales_viernes_horario_atencion = col_character(), 
                                                                                  sucursales_sabado_horario_atencion = col_character(), 
                                                                                  sucursales_domingo_horario_atencion = col_character()), 
                             trim_ws = TRUE)
sucursales_3011 = read_delim("bases/sepa_1_comercio-sepa-3001_2024-09-12_09-05-11/sucursales.csv", 
                             delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                  id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                  sucursales_nombre = col_character(), 
                                                                                  sucursales_tipo = col_character(), 
                                                                                  sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                  sucursales_latitud = col_double(), 
                                                                                  sucursales_longitud = col_double(), 
                                                                                  sucursales_observaciones = col_skip(), 
                                                                                  sucursales_codigo_postal = col_skip(), 
                                                                                  sucursales_localidad = col_character(), 
                                                                                  sucursales_provincia = col_character(), 
                                                                                  sucursales_lunes_horario_atencion = col_character(), 
                                                                                  sucursales_martes_horario_atencion = col_character(), 
                                                                                  sucursales_miercoles_horario_atencion = col_character(), 
                                                                                  sucursales_jueves_horario_atencion = col_character(), 
                                                                                  sucursales_viernes_horario_atencion = col_character(), 
                                                                                  sucursales_sabado_horario_atencion = col_character(), 
                                                                                  sucursales_domingo_horario_atencion = col_character()), 
                             trim_ws = TRUE)
sucursales_5 = read_delim("bases/sepa_2_comercio-sepa-5_2024-09-12_01-05-12/sucursales.csv", 
                          delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                               id_bandera = col_character(), id_sucursal = col_character(), 
                                                                               sucursales_nombre = col_character(), 
                                                                               sucursales_tipo = col_character(), 
                                                                               sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                               sucursales_latitud = col_double(), 
                                                                               sucursales_longitud = col_double(), 
                                                                               sucursales_observaciones = col_skip(), 
                                                                               sucursales_codigo_postal = col_skip(), 
                                                                               sucursales_localidad = col_character(), 
                                                                               sucursales_provincia = col_character(), 
                                                                               sucursales_lunes_horario_atencion = col_character(), 
                                                                               sucursales_martes_horario_atencion = col_character(), 
                                                                               sucursales_miercoles_horario_atencion = col_character(), 
                                                                               sucursales_jueves_horario_atencion = col_character(), 
                                                                               sucursales_viernes_horario_atencion = col_character(), 
                                                                               sucursales_sabado_horario_atencion = col_character(), 
                                                                               sucursales_domingo_horario_atencion = col_character()), 
                          trim_ws = TRUE)
sucursales_6 = read_delim("bases/sepa_2_comercio-sepa-6_2024-09-12_01-05-12/sucursales.csv", 
                          delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                               id_bandera = col_character(), id_sucursal = col_character(), 
                                                                               sucursales_nombre = col_character(), 
                                                                               sucursales_tipo = col_character(), 
                                                                               sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                               sucursales_latitud = col_double(), 
                                                                               sucursales_longitud = col_double(), 
                                                                               sucursales_observaciones = col_skip(), 
                                                                               sucursales_codigo_postal = col_skip(), 
                                                                               sucursales_localidad = col_character(), 
                                                                               sucursales_provincia = col_character(), 
                                                                               sucursales_lunes_horario_atencion = col_character(), 
                                                                               sucursales_martes_horario_atencion = col_character(), 
                                                                               sucursales_miercoles_horario_atencion = col_character(), 
                                                                               sucursales_jueves_horario_atencion = col_character(), 
                                                                               sucursales_viernes_horario_atencion = col_character(), 
                                                                               sucursales_sabado_horario_atencion = col_character(), 
                                                                               sucursales_domingo_horario_atencion = col_character()), 
                          trim_ws = TRUE)
sucursales_10 = read_delim("bases/sepa_2_comercio-sepa-10_2024-09-12_01-05-12/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_11 = read_delim("bases/sepa_2_comercio-sepa-11_2024-09-12_01-05-12/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_13 = read_delim("bases/sepa_2_comercio-sepa-13_2024-09-12_01-05-12/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_22 = read_delim("bases/sepa_2_comercio-sepa-22_2024-09-12_01-05-12/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_36 = read_delim("bases/sepa_2_comercio-sepa-36_2024-09-12_01-05-12/sucursales.csv", 
                           delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                sucursales_nombre = col_character(), 
                                                                                sucursales_tipo = col_character(), 
                                                                                sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                sucursales_latitud = col_double(), 
                                                                                sucursales_longitud = col_double(), 
                                                                                sucursales_observaciones = col_skip(), 
                                                                                sucursales_codigo_postal = col_skip(), 
                                                                                sucursales_localidad = col_character(), 
                                                                                sucursales_provincia = col_character(), 
                                                                                sucursales_lunes_horario_atencion = col_character(), 
                                                                                sucursales_martes_horario_atencion = col_character(), 
                                                                                sucursales_miercoles_horario_atencion = col_character(), 
                                                                                sucursales_jueves_horario_atencion = col_character(), 
                                                                                sucursales_viernes_horario_atencion = col_character(), 
                                                                                sucursales_sabado_horario_atencion = col_character(), 
                                                                                sucursales_domingo_horario_atencion = col_character()), 
                           trim_ws = TRUE)
sucursales_2013 = read_delim("bases/sepa_2_comercio-sepa-2013_2024-09-12_01-05-12/sucursales.csv", 
                             delim = "|", escape_double = FALSE, col_types = cols(id_comercio = col_character(), 
                                                                                  id_bandera = col_character(), id_sucursal = col_character(), 
                                                                                  sucursales_nombre = col_character(), 
                                                                                  sucursales_tipo = col_character(), 
                                                                                  sucursales_calle = col_skip(), sucursales_numero = col_skip(), 
                                                                                  sucursales_latitud = col_double(), 
                                                                                  sucursales_longitud = col_double(), 
                                                                                  sucursales_observaciones = col_skip(), 
                                                                                  sucursales_codigo_postal = col_skip(), 
                                                                                  sucursales_localidad = col_character(), 
                                                                                  sucursales_provincia = col_character(), 
                                                                                  sucursales_lunes_horario_atencion = col_character(), 
                                                                                  sucursales_martes_horario_atencion = col_character(), 
                                                                                  sucursales_miercoles_horario_atencion = col_character(), 
                                                                                  sucursales_jueves_horario_atencion = col_character(), 
                                                                                  sucursales_viernes_horario_atencion = col_character(), 
                                                                                  sucursales_sabado_horario_atencion = col_character(), 
                                                                                  sucursales_domingo_horario_atencion = col_character()), 
                             trim_ws = TRUE)


# Uno las bases en un solo dataframe
sucursales <- bind_rows(
  sucursales_3, sucursales_4, sucursales_9, sucursales_12, sucursales_15, sucursales_16, 
  sucursales_19, sucursales_20, sucursales_21, sucursales_23, sucursales_35, sucursales_47, 
  sucursales_1000, sucursales_2000, sucursales_2005, sucursales_2007, sucursales_2011, 
  sucursales_3011, sucursales_5, sucursales_6, sucursales_10, sucursales_11, sucursales_13, 
  sucursales_22, sucursales_36, sucursales_2013
)

sucursales <- sucursales %>%
  filter(!grepl("^Última actualización", id_comercio))

View(sucursales)


  